language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
#  - Squeak-trunk
#  - Squeak-5.1
#  - Squeak-5.0
#  - Squeak-4.6
#  - Squeak-4.5

#  - Pharo-alpha
#  - Pharo-stable
  - Pharo32-8.0
  - Pharo-7.0
  - Pharo-6.1
#  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0

#  - Pharo64-alpha
#  - Pharo64-stable
  - Pharo64-8.0
  - Pharo64-7.0
  - Pharo64-6.1

#  - GemStone-3.3.0
#  - GemStone-3.2.12
#  - GemStone-3.1.0.6

# Uncomment to enable caching (only useful for GemStone builds (3x faster))
#cache:
#  directories:
#    - $SMALLTALK_CI_CACHE
